### PR TITLE
Change to use absolute and apparent wind

### PR DESCRIPTION
**Pull request by Tebazil12**
Fixes https://github.com/boatd/boatd/issues/58

### CODE REVIEW

**Comment by Danyc0** [comment]
We've been using the term "relative wind" for a long time, if it's changed to "apparent wind" then we need to change it everywhere else. Was this a decision that's been made?

**Comment by Tebazil12** [comment]
The term 'relative wind' was more ambiguous than 'apparent wind'. 'Relative' could mean relative to the boat or world, and we don't want to get those mixed up anymore, so yea we are going to replace it everywhere.

**Comment by Danyc0** [comment]
Ok, I opened #74 for that then, which should probably be merged at the same time as this, otherwise it'll get even more confusing

**Comment by Danyc0** [comment]
however boatd/python-boatd#17 needs to be fixed at the same time this is merged otherwise it will stop working

**Pull request merged**
