### PR TITLE
use correct Coveralls badge

### PR DESCRIPTION
**Pull request by zuzak**
This isn't Jekyll.

### CODE REVIEW

**Comment by kragniz** [comment]
That's a bit embarrassing :shipit:

**Comment by kragniz** [comment]
I thought the coverage was a bit high

**Comment by SamStudio8** [comment]
:cat:

**Comment by zuzak** [comment]
:star2: you tried :star2:

**Comment by kragniz** [comment]
It was correct until 39ef69caff142ec50d0425308d1612b9254d6607

**Pull request merged**
